### ISSUE TITLE
Error when attaching file to task

### ISSUE THREAD

**Issue by ChristianAE** [thewhitetulip/Tasks#18]
I get the following error when trying to attach a file to a task:

```
2016/05/15 21:53:27 inside task query
2016/05/15 21:53:27 table files has 4 columns but 2 values were supplied
2016/05/15 21:53:27 http: panic serving [::1]:60501: runtime error: invalid memory address or nil pointer dereference
goroutine 90 [running]:
net/http.(*conn).serve.func1(0xc820366e80)
    /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x45e2ec0, 0xc82000a0d0)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
database/sql.(*Tx).Stmt(0xc820454ff0, 0x0, 0x1d)
    /usr/local/go/src/database/sql/sql.go:1341 +0x32
github.com/thewhitetulip/Tasks/db.taskQuery(0x46ef900, 0x1d, 0xc8204d3690, 0x2, 0x2, 0x0, 0x0)
    /Users/christian/Development/Go/src/github.com/thewhitetulip/Tasks/db/tasks.go:254 +0x172
github.com/thewhitetulip/Tasks/db.AddFile(0xc8204c8720, 0x26, 0xc820322fe0, 0x20, 0x0, 0x0)
    /Users/christian/Development/Go/src/github.com/thewhitetulip/Tasks/db/files.go:15 +0x187
github.com/thewhitetulip/Tasks/views.AddTaskFunc(0x5a5ce20, 0xc82045eea0, 0xc820508b60)
    /Users/christian/Development/Go/src/github.com/thewhitetulip/Tasks/views/addViews.go:98 +0xe9e
github.com/thewhitetulip/Tasks/views.RequiresLogin.func1(0x5a5ce20, 0xc82045eea0, 0xc820508b60)
    /Users/christian/Development/Go/src/github.com/thewhitetulip/Tasks/views/sessionViews.go:18 +0x95
net/http.HandlerFunc.ServeHTTP(0xc820210720, 0x5a5ce20, 0xc82045eea0, 0xc820508b60)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820062a80, 0x5a5ce20, 0xc82045eea0, 0xc820508b60)
    /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820232400, 0x5a5ce20, 0xc82045eea0, 0xc820508b60)
    /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820366e80)
    /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2137 +0x44e
```

A copy of the file is placed in the _files_ folder.

This line of code seem to build the SQL to write to the database: `err := taskQuery("insert into files values(?,?)", fileName, token)`. The error reads `table files has 4 columns but 2 values were supplied`. Since the SQL provides only two values this seems to be the issue.

I created a pullrequest fixing this issue: https://github.com/thewhitetulip/Tasks/pull/19

**Comment by ChristianAE** [comment]
Fixed with https://github.com/thewhitetulip/Tasks/issues/19

**Comment by thewhitetulip** [comment]
Thank  you 👍
